import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {applyDraftWeights,calculateStandings,pairKey} from '../docs/assets/engine.js';
import {getPlayoffBracket,getPlayoffGames,getBoxscore} from './nhl-client.mjs';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const cfg=JSON.parse(await fs.readFile(path.join(ROOT,'config/live.json'),'utf8'));
if(!cfg.enabled){console.log('Live season is disabled; historical site data left unchanged.');process.exit(0)}
validate(cfg);
const {selections,scale}=applyDraftWeights(cfg.selections,cfg.draftValue),owners=cfg.entrants.map(e=>e.name),players=new Map(selections.filter(s=>s.type==='player').map(s=>[Number(s.playerId),s]));
for(const s of selections){s.stats=s.type==='player'?{gp:0,goals:0,assists:0,points:0,roundPoints:[0,0,0,0]}:{gp:0,wins:0,seriesWins:0,points:0,roundPoints:[0,0,0,0]};s.active=true}
let raw=null;try{raw=await getPlayoffBracket(cfg.season)}catch(e){console.warn(`Bracket unavailable: ${e.message}`)}
const bracket=normalizeBracket(raw),teams=[...new Set([...bracket.series.flatMap(s=>[s.teamA,s.teamB]),...selections.map(s=>s.teamAbbrev)].filter(Boolean))],games=await getPlayoffGames(teams,cfg.seasonId),complete=games.filter(g=>['OFF','FINAL'].includes(String(g.gameState||g.gameScheduleState||'').toUpperCase()));
console.log(`Found ${games.length} playoff games; ${complete.length} completed.`);
const pairRound=new Map(bracket.series.map(s=>[pairKey(s.teamAId??s.teamA,s.teamBId??s.teamB),s.round])),seriesWins=new Map(),roundTotals=Object.fromEntries(owners.map(n=>[n,[0,0,0,0]])),daily=new Map();
for(const game of complete){const box=await getBoxscore(game.id),awayId=box.awayTeam?.id??game.awayTeam?.id,homeId=box.homeTeam?.id??game.homeTeam?.id,away=box.awayTeam?.abbrev??game.awayTeam?.abbrev,home=box.homeTeam?.abbrev??game.homeTeam?.abbrev,key=pairKey(awayId??away,homeId??home),round=pairRound.get(key)||Number(game.seriesStatus?.round||box.seriesStatus?.round||1),day=dateTZ(game.startTimeUTC||box.startTimeUTC||`${game.gameDate}T12:00:00Z`,cfg.timezone);if(!daily.has(day))daily.set(day,Object.fromEntries(owners.map(n=>[n,0])));const add=daily.get(day),seen=new Set();for(const p of flatten(box.playerByGameStats)){const pick=players.get(Number(p.playerId));if(!pick)continue;if(!seen.has(pick.playerId)){pick.stats.gp++;seen.add(pick.playerId)}const g=Number(p.goals||0),a=Number(p.assists||0),pts=g*cfg.scoring.playerGoal+a*cfg.scoring.playerAssist;pick.stats.goals+=g;pick.stats.assists+=a;pick.stats.points+=pts;pick.stats.roundPoints[round-1]+=pts;add[pick.owner]+=pts;roundTotals[pick.owner][round-1]+=pts}const as=Number(box.awayTeam?.score??game.awayTeam?.score??0),hs=Number(box.homeTeam?.score??game.homeTeam?.score??0),winner=as>hs?away:home,winnerId=as>hs?awayId:homeId;for(const p of selections.filter(s=>s.type==='team'&&(s.teamAbbrev===away||s.teamAbbrev===home)))p.stats.gp++;for(const p of selections.filter(s=>s.type==='team'&&s.teamAbbrev===winner)){p.stats.wins++;p.stats.points+=cfg.scoring.teamWin;p.stats.roundPoints[round-1]+=cfg.scoring.teamWin;add[p.owner]+=cfg.scoring.teamWin;roundTotals[p.owner][round-1]+=cfg.scoring.teamWin}const state=seriesWins.get(key)||{};state[winnerId]=(state[winnerId]||0)+1;seriesWins.set(key,state);if(state[winnerId]===4)for(const p of selections.filter(s=>s.type==='team'&&s.teamAbbrev===winner)){p.stats.seriesWins++;p.stats.points+=cfg.scoring.seriesWin;p.stats.roundPoints[round-1]+=cfg.scoring.seriesWin;add[p.owner]+=cfg.scoring.seriesWin;roundTotals[p.owner][round-1]+=cfg.scoring.seriesWin}}
const finalDone=bracket.series.some(s=>s.round===4&&s.complete),eliminated=new Set(bracket.series.filter(s=>s.complete&&s.loser).map(s=>s.loser));for(const s of selections)s.active=!finalDone&&!eliminated.has(s.teamAbbrev);
const history=buildHistory(daily,owners),yesterday=dateTZ(new Date(Date.now()-86400000).toISOString(),cfg.timezone),lastNight=daily.get(yesterday)||Object.fromEntries(owners.map(n=>[n,0])),standings=calculateStandings(selections,cfg.entrants,lastNight),summary=buildSummary(selections,owners,roundTotals);
const data={schemaVersion:1,season:cfg.season,seasonId:cfg.seasonId,poolName:cfg.poolName,timezone:cfg.timezone,status:finalDone?'complete':'live',source:'NHL web data',lastUpdated:new Date().toISOString(),entrants:cfg.entrants,scoring:cfg.scoring,draftValue:cfg.draftValue,draftWeightScale:scale,selections,standings,summary,history,bracket};
await fs.writeFile(path.join(ROOT,'docs/data',`${cfg.season}.json`),JSON.stringify(data,null,2));const idxPath=path.join(ROOT,'docs/data/seasons.json'),idx=JSON.parse(await fs.readFile(idxPath,'utf8'));idx.seasons=idx.seasons.filter(s=>s.season!==cfg.season).concat({season:cfg.season,label:String(cfg.season),file:`data/${cfg.season}.json`,status:data.status}).sort((a,b)=>a.season-b.season);idx.defaultSeason=cfg.season;await fs.writeFile(idxPath,JSON.stringify(idx,null,2));console.log(`Leader: ${standings[0]?.owner} ${standings[0]?.total}`);
function validate(c){const owners=new Set(c.entrants.map(e=>e.name)),nums=new Set(),picks=new Set();for(const s of c.selections){if(!owners.has(s.owner))throw Error(`Unknown owner ${s.owner}`);if(nums.has(s.draftNumber))throw Error(`Duplicate draft #${s.draftNumber}`);nums.add(s.draftNumber);const key=s.type==='player'?`p:${s.playerId}`:`t:${s.teamAbbrev}`;if(picks.has(key))throw Error(`Duplicate selection ${key}`);picks.add(key);if(s.type==='player'&&!Number.isInteger(Number(s.playerId)))throw Error(`Missing NHL playerId for ${s.name}`);if(!s.teamAbbrev)throw Error(`Missing team for ${s.name}`)}}
function flatten(p){if(!p)return[];const out=[];for(const side of[p.awayTeam,p.homeTeam].filter(Boolean))for(const k of['forwards','defense','goalies'])if(Array.isArray(side[k]))out.push(...side[k]);return out}
function normalizeBracket(raw){const series=(raw?.series||[]).map(s=>({round:Number(s.playoffRound),letter:s.seriesLetter,teamA:s.topSeedTeam?.abbrev||null,teamAId:s.topSeedTeam?.id||null,winsA:Number(s.topSeedWins||0),teamB:s.bottomSeedTeam?.abbrev||null,teamBId:s.bottomSeedTeam?.id||null,winsB:Number(s.bottomSeedWins||0),winner:s.winningTeamId?(s.winningTeamId===s.topSeedTeam?.id?s.topSeedTeam?.abbrev:s.bottomSeedTeam?.abbrev):null,loser:s.losingTeamId?(s.losingTeamId===s.topSeedTeam?.id?s.topSeedTeam?.abbrev:s.bottomSeedTeam?.abbrev):null,complete:Boolean(s.winningTeamId)}));const f=series.find(s=>s.round===4);return{series,champion:f?.winner||null,complete:Boolean(f?.winner)}}
function dateTZ(input,timeZone){const p=new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(input)),g=t=>p.find(x=>x.type===t)?.value;return`${g('year')}-${g('month')}-${g('day')}`}
function buildHistory(daily,names){const dates=[...daily.keys()].sort();if(!dates.length)return[];const start=new Date(`${dates[0]}T12:00:00Z`),end=new Date(`${dates.at(-1)}T12:00:00Z`),tot=Object.fromEntries(names.map(n=>[n,0])),out=[];for(let d=new Date(start);d<=end;d.setUTCDate(d.getUTCDate()+1)){const k=d.toISOString().slice(0,10),a=daily.get(k)||{};for(const n of names)tot[n]+=a[n]||0;out.push({date:k,...tot})}return out}
function buildSummary(sel,names,roundTotals){const playerTotals={},teamTotals={};for(const n of names){const ps=sel.filter(s=>s.owner===n&&s.type==='player'),ts=sel.filter(s=>s.owner===n&&s.type==='team'),gp=ps.reduce((a,s)=>a+s.stats.gp,0),goals=ps.reduce((a,s)=>a+s.stats.goals,0),assists=ps.reduce((a,s)=>a+s.stats.assists,0),points=goals+assists;playerTotals[n]={gp,avgPpg:gp?points/gp:0,goals,assists,points};const rounds=[0,1,2,3].map(i=>ts.reduce((a,s)=>a+(s.stats.roundPoints[i]||0),0));teamTotals[n]={rounds,total:rounds.reduce((a,b)=>a+b,0)}}return{playerTotals,teamTotals,pointsLastNight:{},roundTotals:Object.fromEntries(names.map(n=>[n,{rounds:roundTotals[n],total:roundTotals[n].reduce((a,b)=>a+b,0)}]))}}
